### ISSUE TITLE
feat: add idl path to [[programs]] config and load the IDL data into the proper account

### ISSUE THREAD

**Issue by thlorenz** [magicblock-labs/bolt#52]
Specifying the below `[[program]]` config:

```toml
[[program]]
id = "wormH7q6y9EBUUL6EyptYhryxs6HoJg8sPK3LMfoNf4"
path = "../../../demos/magic-worm/target/deploy/program_solana.so"
idl = "../../../demos/magic-worm/idls/program_solana.json"
```

should do the following:

1. as usual load the program at the given path into the validator
2. determine the IDL address and load it compressed into the validator

This was already implemented in Luzid and we most likely just can move it into our validator and adapt it slightly.
